ABCar/WebApp/Areas/Admin/Controllers/EvidencijaZaposlenikaController.cs
using System;
using ABCar.Business;
using ABCar.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace ABCar.WebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [ActionFilter(admin: true)]
    public class EvidencijaZaposlenikaController : Controller
    {
        private ZaposlenikOperations zaposlenikOperations { get; set; }

        public EvidencijaZaposlenikaController()
        {
            zaposlenikOperations = new ZaposlenikOperations();
        }

        public IActionResult SviZaposlenici()
        {
            return View(zaposlenikOperations.GetAll());
        }

        public IActionResult DodajNovogZaposlenika()
        {
            return View(new DodajZaposlenikaVM { DatumZaposljenja = DateTime.Today });
        }

        [HttpPost]
        public IActionResult DodajNovogZaposlenika(DodajZaposlenikaVM model)
        {
            if (!ModelState.IsValid)
                return View(model);

            if (new KorisnickiRacunOperations().IsUsernameUsed(model.Username))
            {
                ViewBag.Error = "Korisnicko ime zauzeto!";
                return View(model);
            }

            zaposlenikOperations.Add(model);

            TempData["Confirmation"] = "Novi zaposlenik uspjesno dodan!";

            return RedirectToAction("SviZaposlenici");
        }

        public IActionResult UrediZaposlenika(int zaposlenikId)
        {
            return View(zaposlenikOperations.GetUrediVMById(zaposlenikId));
        }

        [HttpPost]
        public IActionResult UrediZaposlenika(UrediZaposlenikaVM model)
        {
            if (!ModelState.IsValid)
                return View(model);


            zaposlenikOperations.Update(model);

            TempData["Confirmation"] = "Zaposlenik uspjesno uredjen!";

            return RedirectToAction("SviZaposlenici");


        }

        public IActionResult ObrisiZaposlenika(int zaposlenikId)
        {
            zaposlenikOperations.Remove(zaposlenikId);

            TempData["Confirmation"] = "Zaposlenik izbrisan!";

            return RedirectToAction("SviZaposlenici");


        }
    }
}

ABCar/WebApp/Areas/Shared/Controllers/AjaxController.cs
using ABCar.Business;
using Microsoft.AspNetCore.Mvc;

namespace ABCar.WebApp.Areas.Shared.Controllers
{
    [Area("Shared")]
    public class AjaxController : Controller
    {
        private readonly VoziloOperations voziloOperations;

        public AjaxController()
        {
            voziloOperations = new VoziloOperations();
        }

        public IActionResult GetModeli(int markaId, int?modelId=null)
        {
            var model = markaId != -1?voziloOperations.GetModeliByMarkaId(markaId,modelId):null;
            return PartialView("Modeli",model);
        }

        public IActionResult GetLogo(int markaId)
        {
            var model = markaId != -1 ? voziloOperations.GetMarkaLogoPath(markaId) : null;
            return PartialView("Logo",model);
        }
    }
}

ABCar/WebApp/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>:: ABCar ::</title>


    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js"></script>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/css/sidebar.css" rel="stylesheet" />
    <link href="~/css/card.css" rel="stylesheet" />


</head>
<body>

    @*SIDEBAR*@
    <div class="col-sm-2">
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">

                @*OVO SLUZI ZA SIDEBAR HEADER!*@
                <li class="sidebar-brand">
                    <a class="navbar-brand" asp-controller="Home" asp-action="Index">ABCar</a>
                </li>

                @* SIDEBAR KOMPONENTE *@
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><strong>Evidencija zaposlenika </strong><span class="caret"></span>@*<span style="font-size:16px;" class="hidden-xs showopacity glyphicon glyphicon-user"></span>*@</a>
                    <ul class="dropdown-menu forAnimate" role="menu">
                        <li>
                            <a asp-controller="EvidencijaZaposlenika" asp-action="DodajNovogZaposlenika">Dodaj novog zaposlenika</a>
                        </li>
                        <li>
                            <a asp-controller="EvidencijaZaposlenika" asp-action="SviZaposlenici">Prikaz zaposlenika</a>
                        </li>
                    </ul>
                </li>
                <li><hr /></li>
                @*<li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><strong>Evidencija lagera </strong><span class="caret"></span>@*<span style="font-size:16px;" class="hidden-xs showopacity glyphicon glyphicon-user"></span></a>
                    <ul class="dropdown-menu forAnimate" role="menu">
                        <li><a>Prikaz lagera</a></li>
                    </ul>
                </li>
                <li><hr /></li>*@
            </ul>
        </div>
    </div>


    @*NAVBAR + PageContent*@
    <div class="col-sm-10" style="padding-left:0px;padding-left:0px;">

        @*NAVBAR*@
        <nav class="navbar navbar-inverse" style="margin-bottom:0px;">
            <div class="container-fluid">
                @*<div class="navbar-header">
                        <a class="navbar-brand" asp-controller="Home" asp-action="Index">ABCar</a>
                    </div>*@

                <ul class="nav navbar-nav navbar-right">
                    @await Component.InvokeAsync(typeof(ABCar.WebApp.ViewComponents.LayoutLoginComponent))
                </ul>
            </div>
        </nav>

        <div class="container" style="padding: 30px;">
            
            @if (TempData["Confirmation"] != null)
            {
                <div id="confirmationMssg" class="alert alert-danger text-center" style="width: 100%;"><span>@TempData["Confirmation"]</span></div>
            }
            @RenderBody()
        </div>

    </div>

</body>
</html>